name: Unity

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: self-hosted
    
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - WebGL # WebGL.
    
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-TestUnityCI-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-TestUnityCI-
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: auto
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        id: buildStep
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: auto
          buildName: TestUnityCI
          buildsPath: build
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          allowDirtyBuild: true # Bad programmer! Bad!

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: TestUnityCI-${{ steps.buildStep.outputs.buildVersion }}-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}/
